version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: receitas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_receitas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./desafio/banco/script.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  mysql_data: