services:
  mysql:
    image: mysql:8.0
    container_name: receitas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_receitas_rg_sistemas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d

volumes:
  mysql_data: